### ISSUE TITLE
address question

### ISSUE THREAD

**Issue by Kalispaa** [Glatrix/Among-Us-Dump#1]
# Offsets Questions <h1>

_**hey hi I would like to know how to get the addresses, just like you did Among us Rework "Main Offset" works only for LocalPlayer allPlayers and game options, I would like to know how to change the PingTracker.Text to something else but it doesn't have the address his in the dump.cs**_

**Comment by Glatrix** [comment]
Sorry for the late response, add me on discord Glatriix#8936
